### ISSUE TITLE
Suggestion: Hard Bundle Rewards

### ISSUE THREAD

**Issue by HanazakiTV** [minervamaga/HarderCCBundles-CP#3]
Hey Minerva,

I was checking the Hard Bundles Rewards and i feel like there a little underwhelming in terms of balancing, for instance:

Summer Crops Hard requires year 2 crops, but gives in return 1 bee hive.
-> This feels a little underwhelming as a reward in terms of challenge provided

I will list my suggested hard rewards below:
#Pantry
Spring: 5 Super Meal
Summer: 5 Desert Totem (Desert is valuable)(Hot Summer = Desert Totems)
Fall: 10 Farm Totems
Quality: 5 Rare or 5 Ancient Seeds
Animal: Auto Grabber instead of Artisan Reward, because Animal Related
Artisan: 5 Kegs or 10 Preserve Jars

#Fish Tank
Spring: 99 Wild Bait (30 feels too little)
Summer: 30 Magnets are fine
Fall: 200 normal Bait for use in Fishing or Crab Potts
Winter: 5 Lobster Bisque instead of Speciality, since Lobster are a Winter Season Animal
Speciality: 2-3 Treasure Chests
CrabPot: 5 Crabcakes are fine

#Crafts
Spring: 2 Quality Sprinklers or 6 Regular Sprinklers
Summer: 5 Energy Tonics
Fall: 5 Life Elexiers is fine
Winter: 1 Crystalarium (fits the blue/white Theme)

#Boiler:
Blacksmith: 1 Iridium Band instead of Sprinklers
Geologist: 1 Prismatic Shard is fine
Adventurer: A Weapon like LavaKatana or The Slammer Hammer to bridge the gap to the galaxy weapons

#Vault:
Vault 1: 10 Coffee (10 Coffee for basicly Halfprice)
Vault 2: 30 Megabombs are fine
Vault 3: 1 Racoon Rarecrow is fine
Vault 4: 1 Stardrop (60k early for permanent energy is a hard but fair trade)

#BulletinBoard
SaloonMenu: 1 JunimoCart Game instead of food (Cooking food to recieve food seems wrong to me because at that point you should have unlimited food)
Field Research: 5-10 Artifact Trove (to fit the notion of a researcher never stops researching)
Enchanter: Napalm Ring or a Slime Charmer Ring would make alot more sense or even go as far as 3-5 ancient seeds
Dye: 10 Rare seeds are fine
Fodder: 5 Dinosaur Eggs are fine

I think those changes would balance out the hard-mode bundles a bit for price/reward.

Have a good one

**Comment by minervamaga** [comment]
Version 1.10.0 adds this, thank you so much!
